auxdisplay: ht16k33: select framebuffer helper modules
The new driver caused a rare randconfig failure:

drivers/auxdisplay/ht16k33.o:(.data.ht16k33_fb_ops+0xc): undefined reference to `fb_sys_read'
drivers/auxdisplay/ht16k33.o:(.data.ht16k33_fb_ops+0x10): undefined reference to `fb_sys_write'

This selects the respective helper modules.

Reported-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Robin van der Gracht <robin@protonic.nl>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>