mmprofile: fix -Werror=unused-variable message
Warning messages:
drivers/misc/mediatek/mmp/src/mmprofile.c:119:21:
error: 'mmprofile_meta_buffer_mutex' defined but not used
[-Werror=unused-variable]
 static DEFINE_MUTEX(mmprofile_meta_buffer_mutex);

Change-Id: I1f6b137d004d7ec869cdc7c14595bf301509aa08
Signed-off-by: Flora Fu <flora.fu@mediatek.com>
CR-Id: AUTO00029458