m68knommu: Fix typos in Coldfire 5272 DMA debug code
If DEBUG_DMA is defined:

    include/asm/dma.h: In function ‘set_dma_mode’:
    include/asm/dma.h:393: error: ‘dmabp’ undeclared (first use in this function)
    include/asm/dma.h:393: error: (Each undeclared identifier is reported only once
    include/asm/dma.h:393: error: for each function it appears in.)
    include/asm/dma.h: In function ‘set_dma_addr’:
    include/asm/dma.h:424: error: ‘dmawp’ undeclared (first use in this function)

Reported-by: kbuild test robot <fengguang.wu@intel.com>
Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>
Signed-off-by: Greg Ungerer <gerg@linux-m68k.org>