[ALPS04969781] UPSTREAM: ethtool: reduce stack usage with clang
clang inlines the dev_ethtool() more aggressively than gcc does, leading
to a larger amount of used stack space:

net/core/ethtool.c:2536:24: error: stack frame size of 1216 bytes in
function dev_ethtool [-Werror,-Wframe-larger-than=]

Marking the sub-functions that require the most stack space as
noinline_for_stack gives us reasonable behavior on all compilers.

MTK-Commit-Id: 0fb5d1a26fc60f77605e6e7a4c60749b245a04c3

Change-Id: Idf10268c48b3e1c4bca5d599efcab78311c161fe
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Reviewed-by: Michal Kubecek <mkubecek@suse.cz>
Signed-off-by: David S. Miller <davem@davemloft.net>
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Feature: [Module]Official Kernel Patch
CR-Id: ALPS04969781