[ALPS05034345] BACKPORT: debugfs: Fix !DEBUG_FS debugfs_create_automount
If DEBUG_FS=n, compile fails with the following error:

kernel/trace/trace.c: In function tracing_init_dentry:
kernel/trace/trace.c:8658:9: error: passing argument 3 of
debugfs_create_automount from incompatible pointer type
[-Werror=incompatible-pointer-types]
 8658 |         trace_automount, NULL);
      |         ^~~~~~~~~~~~~~~
      |         |
      |         struct vfsmount * (*)(struct dentry *, void *)
In file included from kernel/trace/trace.c:24:
./include/linux/debugfs.h:206:25: note: expected struct vfsmount *
(*)(void *) but argument is of type struct vfsmount * (*)(struct dentry
*, void *)
  206 |      struct vfsmount *(*f)(void *),
      |      ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~

Signed-off-by: Kusanagi Kouichi <slash@ac.auone-net.jp>
Link:
https://lore.kernel.org/r/20191121102021787.MLMY.25002.ppp.dion.ne.jp@dmta0003.auone-net.jp
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
(cherry picked from commit 4250b047039d324e0ff65267c8beb5bad5052a86)
Signed-off-by: Greg Kroah-Hartman <gregkh@google.com>

MTK-Commit-Id: 89c7cc5744d12d51bd2f6ea9dfe7c5cc98dd3a43

Change-Id: I5871c3764fa9211b38eba0b87b3e0ed4f8f5e180
Signed-off-by: Jades Shih <jades.shih@mediatek.com>
CR-Id: ALPS05034345
Feature: [Module]Kernel Maintenance